//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2


use proto::ds_user::DsUser;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_ds_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_name: Option<String>,
    pub user_password: Option<String>,
    pub user_type: Option<i32>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub tenant_id: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub queue: Option<String>,
    pub state: Option<i32>,
    pub time_zone: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
impl From<Model> for DsUser {
    fn from(model: Model) -> Self {
        Self {
            id: model.id,
            user_name: model.user_name,
            user_password: model.user_password,
            user_type: model.user_type,
            email: model.email,
            phone: model.phone,
            tenant_id: model.tenant_id,
            create_time: model.create_time.map(|x| x.to_string()),
            update_time: model.update_time.map(|x| x.to_string()),
            queue: model.queue,
            state: model.state,
            time_zone: model.time_zone,
        }
    }
}
