
###
POST http://127.0.0.1:12345/message HTTP/1.1
content-type: application/json

{
    "id": 12,
    "contents": "dolphinscheduler123"
}
###
GET  http://127.0.0.1:12345/users HTTP/1.1



###
curl 'http://pt003:12345/dolphinscheduler/login' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: sessionId=bbae7f91-54f4-4f62-956e-566c943e0314; _ga=GA1.1.1260917633.1679362249; csrftoken=cau9yGs64fECWvFjv26ilGb23IG3PNOnCExY5mVIuQtGE4IhuP9DMtpcazyBFw71; session=.eJwlz0FuAzEIheG7eD0L24CBXGaEgVGjRI00k6yq3r2WeoDv13s_ZT_OvL7K7X1-civ7PcqtiEKfA8ncezU46uGMdSr21kcLxTnVxIV0CDTUJCWA6JO6tfB0IpMwhWmKjLQKKCEjeUIbFXUVvNUR2bgzRqRJRoKkQo3AshW_zmN_vx75vfaoc200DmDjbB7CbF4VbHQbCQjkjjJkuefL7ZnLLLiVz5Xn_6VWfv8As35CRg.ZGXNww.HSLrVtXIJV8Jae64zw8CZpBL0y8; language=zh_CN' \
  -H 'Origin: http://pt003:12345' \
  -H 'Pragma: no-cache' \
  -H 'Referrer: http://pt003:12345/dolphinscheduler/ui/login' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'language: zh_CN' \
  -H 'sessionId;' \
  --data-raw 'userName=admin&userPassword=dolphinscheduler123' \
  --compressed \
  --insecure
## login
curl 'http://pt003:12345/dolphinscheduler/login' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'sessionId;' \
  -H 'Referrer: http://pt003:12345/dolphinscheduler/ui/login' \
  -H 'language: zh_CN' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-raw 'userName=admin&userPassword=dolphinscheduler123' \
  --compressed \
  --insecure

  ## get user info
  curl 'http://pt003:12345/dolphinscheduler/users/get-user-info' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'sessionId: 83c7571c-b88a-4229-9038-1b918e069de3' \
  -H 'Referrer: http://pt003:12345/dolphinscheduler/ui/login' \
  -H 'language: zh_CN' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --compressed \
  --insecure

  ###
  curl 'http://pt003:12345/dolphinscheduler/users/get-user-info' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: sessionId=d328eda2-9b2e-4fed-9c6a-66c764251ddb; _ga=GA1.1.1260917633.1679362249; csrftoken=cau9yGs64fECWvFjv26ilGb23IG3PNOnCExY5mVIuQtGE4IhuP9DMtpcazyBFw71; session=.eJwlz0FuAzEIheG7eD0L24CBXGaEgVGjRI00k6yq3r2WeoDv13s_ZT_OvL7K7X1-civ7PcqtiEKfA8ncezU46uGMdSr21kcLxTnVxIV0CDTUJCWA6JO6tfB0IpMwhWmKjLQKKCEjeUIbFXUVvNUR2bgzRqRJRoKkQo3AshW_zmN_vx75vfaoc200DmDjbB7CbF4VbHQbCQjkjjJkuefL7ZnLLLiVz5Xn_6VWfv8As35CRg.ZGXNww.HSLrVtXIJV8Jae64zw8CZpBL0y8; language=zh_CN' \
  -H 'Pragma: no-cache' \
  -H 'Referrer: http://pt003:12345/dolphinscheduler/ui/login' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'language: zh_CN' \
  -H 'sessionId: d328eda2-9b2e-4fed-9c6a-66c764251ddb' \
  --compressed \
  --insecure

###
POST  http://127.0.0.1:12345/authorize HTTP/1.1
content-type:  application/json

{
    "client_id": "admin",
    "client_secret": "dolphinscheduler123"
}

###
POST http://127.0.0.1:12345/authorize HTTP/1.1
content-type: application/json

{
     "client_id": "admin",
    "client_secret": "dolphinscheduler123"
}

###
POST http://127.0.0.1:12345/get_user HTTP/1.1
content-type: application/json

{
    "username": "admin111"
}


###
POST http://127.0.0.1:12345/get_user HTTP/1.1
content-type: application/json

{
    "username": "admin"
}
